"""Game engine components for AutoWerewolf."""

from .roles import (
    Role,
    Alignment,
    Phase,
    WinningTeam,
    WinMode,
    RoleSet,
    get_role_composition,
)
from .state import (
    Player,
    GameConfig,
    RuleVariants,
    GameState,
    Event,
    Action,
    EventType,
    ActionType,
    NightResolution,
    VoteResult,
)
from .rules import (
    create_game_state,
    validate_role_composition,
    resolve_night_actions,
    resolve_sheriff_election,
    resolve_vote,
    resolve_lynch,
    resolve_badge_action,
    resolve_hunter_shot,
    resolve_wolf_self_explode,
    check_win_condition,
    update_win_condition,
    advance_to_day,
    advance_to_night,
    get_valid_wolf_targets,
    get_valid_guard_targets,
    get_valid_vote_targets,
    get_valid_hunter_targets,
    can_witch_cure,
    can_witch_poison,
    can_hunter_shoot,
)

__all__ = [
    # Enums
    "Role",
    "Alignment", 
    "Phase",
    "WinningTeam",
    "WinMode",
    "RoleSet",
    "EventType",
    "ActionType",
    # Models
    "Player",
    "GameConfig",
    "RuleVariants",
    "GameState",
    "Event",
    "Action",
    "NightResolution",
    "VoteResult",
    # Functions
    "get_role_composition",
    "create_game_state",
    "validate_role_composition",
    "resolve_night_actions",
    "resolve_sheriff_election",
    "resolve_vote",
    "resolve_lynch",
    "resolve_badge_action",
    "resolve_hunter_shot",
    "resolve_wolf_self_explode",
    "check_win_condition",
    "update_win_condition",
    "advance_to_day",
    "advance_to_night",
    "get_valid_wolf_targets",
    "get_valid_guard_targets",
    "get_valid_vote_targets",
    "get_valid_hunter_targets",
    "can_witch_cure",
    "can_witch_poison",
    "can_hunter_shoot",
]
