"""LangChain-based agents for AutoWerewolf."""

from autowerewolf.agents.backend import get_chat_model
from autowerewolf.agents.batch import (
    BatchExecutor,
    BatchRequest,
    BatchResult,
    RateLimiter,
    create_batch_executor,
)
from autowerewolf.agents.human import (
    CLIInputHandler,
    HumanPlayerAgent,
    WebInputHandler,
    create_human_agent,
)
from autowerewolf.agents.memory import (
    AgentMemory,
    ConversationMemory,
    GameFact,
    GameFactMemory,
    FactType,
    WerewolfCampMemory,
    create_agent_memory,
    create_werewolf_camp_memory,
)
from autowerewolf.agents.moderator import ModeratorChain, NarrationOutput
from autowerewolf.agents.player_base import (
    BasePlayerAgent,
    GameView,
    create_player_agent,
)
from autowerewolf.agents.roles import (
    GuardAgent,
    HunterAgent,
    ROLE_AGENT_MAP,
    SeerAgent,
    VillageIdiotAgent,
    VillagerAgent,
    WerewolfAgent,
    WitchAgent,
)
from autowerewolf.agents.prompts import (
    MINIMAL_PROMPTS,
    STANDARD_PROMPTS,
    FULL_PROMPTS,
    PROMPTS_BY_VERBOSITY,
    PromptKey,
    format_prompt,
    get_base_system_prompt,
    get_prompt,
    get_role_system_prompt,
)
from autowerewolf.agents.schemas import (
    BadgeDecisionOutput,
    GuardNightOutput,
    HunterShootOutput,
    LastWordsOutput,
    NightActionOutput,
    SeerNightOutput,
    SheriffDecisionOutput,
    SheriffSpeechOutput,
    SheriffVoteOutput,
    SpeechOutput,
    VoteOutput,
    WerewolfNightOutput,
    WerewolfProposalOutput,
    WitchNightOutput,
)

__all__ = [
    "get_chat_model",
    "BatchExecutor",
    "BatchRequest",
    "BatchResult",
    "RateLimiter",
    "create_batch_executor",
    "HumanPlayerAgent",
    "CLIInputHandler",
    "WebInputHandler",
    "create_human_agent",
    "AgentMemory",
    "ConversationMemory",
    "GameFact",
    "GameFactMemory",
    "FactType",
    "WerewolfCampMemory",
    "create_agent_memory",
    "create_werewolf_camp_memory",
    "ModeratorChain",
    "NarrationOutput",
    "BasePlayerAgent",
    "GameView",
    "VillagerAgent",
    "WerewolfAgent",
    "SeerAgent",
    "WitchAgent",
    "HunterAgent",
    "GuardAgent",
    "VillageIdiotAgent",
    "ROLE_AGENT_MAP",
    "create_player_agent",
    "MINIMAL_PROMPTS",
    "STANDARD_PROMPTS",
    "FULL_PROMPTS",
    "PROMPTS_BY_VERBOSITY",
    "PromptKey",
    "format_prompt",
    "get_base_system_prompt",
    "get_prompt",
    "get_role_system_prompt",
    "SpeechOutput",
    "LastWordsOutput",
    "VoteOutput",
    "NightActionOutput",
    "SheriffDecisionOutput",
    "SheriffSpeechOutput",
    "SheriffVoteOutput",
    "BadgeDecisionOutput",
    "WerewolfNightOutput",
    "WerewolfProposalOutput",
    "SeerNightOutput",
    "WitchNightOutput",
    "GuardNightOutput",
    "HunterShootOutput",
]
